// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "API Support",
            "email": "support@healy-medicare.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/google/redirect": {
            "get": {
                "security": [
                    {
                        "None": []
                    }
                ],
                "description": "Handles the callback from Google OAuth2 login",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Patients"
                ],
                "summary": "Handle Google OAuth2 callback",
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.GoogleUserInfo"
                        }
                    },
                    "400": {
                        "description": "No code in query parameters",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Failed to exchange token",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/patient/login": {
            "get": {
                "security": [
                    {
                        "None": []
                    }
                ],
                "description": "Redirects the user to Google's OAuth2 login page",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Patients"
                ],
                "summary": "Redirect to Google OAuth2 login",
                "responses": {
                    "302": {
                        "description": "Redirecting to Google login",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/patient/profile": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Retrieve details of a specific patient",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Patient Profile"
                ],
                "summary": "Get patient details",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.GoogleUserInfo": {
            "type": "object",
            "properties": {
                "accesstoken": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "description": "Google's unique user ID",
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "refreshtoken": {
                    "type": "string"
                },
                "tokenexpiry": {
                    "type": "string"
                }
            }
        },
        "response.Response": {
            "type": "object",
            "properties": {
                "data": {
                    "description": "The response data\nexample: {\"key\": \"value\"}"
                },
                "error": {
                    "description": "The error information, if any\nexample: \"Error description\""
                },
                "message": {
                    "description": "The response message\nexample: \"Request was successful\"",
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "Bearer": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Healy Medicare API",
	Description:      "This is the API documentation for the Healy Medicare application.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
